# This is a basic workflow to help you get started with Actions

name: Generate All Docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [addtree_continued]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy gurobipy
          pip install -U scikit-learn

      - name: Install veritas
        run: |
          git submodule init && git submodule update
          pip install --editable . 
          mkdir manual_build
          cd manual_build
          cmake ..
          make -j4
          ln -sfr veritas_core.cpython-*.so ../src/python/veritas/

      - name: Install Docs dependencies
        run: |
          pip install sphinx sphinx_rtd_theme breathe

      - name: Generate python_examples
        run: python docs/generate_python_examples.py

      - name: Doxygen Install
        run: sudo apt-get install doxygen -y

      - name: Generate all docs
        run: cd docs && make html

      - name: Deploy pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages-sphinx
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/
          force_orphan: true
